### ISSUE TITLE
Overlap of text and footer line on first page (SR)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/csasdowntex#145]
Working on the herring SR. The text overlaps the footer line on the first page:
![image](https://user-images.githubusercontent.com/25674027/92177022-8b1da380-edf4-11ea-9a11-eeea3d4dd0a6.png)

**Comment by seananderson** [comment]
The first thing I would try would be increasing the bottom margin slightly. The paragraph/line spacing here might have exposed that it should be slightly larger than it is.
https://github.com/pbs-assess/csasdown/blob/81eed29b66c6e3b694d53a9a2fd1b87f0314e40a/inst/csas-style/sr.sty#L49
but I could be wrong and it could be controlled somewhere else.

**Comment by grinnellm** [comment]
It was fixed with `bottom=1.8in` but then we updated the text on the first page and it's overlapping again. I increased it to `bottom=1.9in` which works, but that's starting to seem pretty large in the rest of the document where this is not an issue. What I'd rather do is just increase the margin on the first page. I thought I could do that in the commands `\fancypagestyle{firstPage}` and `\newcommand{\MakeFirstPage}` but it doesn't seem to work, at least that I can figure out. I thought this would be in the `\newgeometry{}` line in `\fancypagestyle{firstPage}`.
https://github.com/pbs-assess/csasdown/blob/81eed29b66c6e3b694d53a9a2fd1b87f0314e40a/inst/csas-style/sr.sty#L550

**Comment by cgrandin** [comment]
I can't replicate this a year after the initial issue was submitted. It all looks good to me even if I make the title really long so it takes up 4 lines.
Maybe it was due to the same thing as #197.
Is it fixed @grinnellm ? If so we can close this

**Comment by grinnellm** [comment]
It's not fixed. It only happens some times depending on where paragraphs start/end and page breaks occur. This is our current SR, but I deleted one bullet.
![image](https://user-images.githubusercontent.com/25674027/150195455-623d7535-98fe-4e6d-a5b0-d5d321846e38.png)

**Comment by cgrandin** [comment]
@grinnellm I tried building this using the SR you attached in #90 and added text to the first section, and it came out fine. Is there another doc you can zip up for me to try? I didn't try the SR from Github because I assumed there would be a data folder needed for it.

I would like to clean up this last lingering issue if possible
Thanks :)

**Comment by grinnellm** [comment]
Here's a file that shows the two remaining issues, and a (new) third one that I just noticed:

1. #145

1. #90 

1. Appendix is pushed to after the section "This report is available.."

[sr.zip](https://github.com/pbs-assess/csasdown/files/8227366/sr.zip)

**Comment by cgrandin** [comment]
I fixed number 2 in 5027ca43428030e4d7259e57e621a5c642285d34

Where is the Appendix supposed to be located?

**Comment by cgrandin** [comment]
@grinnellm  So the line overlapping is fixed, but it was just by changing the size of the "Canada" image on the first page. If we can't change it, then we will have to change the footers for the whole document instead. Hopefully this works though. If it does, go ahead and close this!

![image](https://user-images.githubusercontent.com/4551051/158233129-7929c174-6ec0-4f70-8664-235afad8cbd5.png)

**Comment by grinnellm** [comment]
Thanks Chris, I hope that works. I don't have time to check this now, so can we leave it Open until I'm sure?
The Appendix section is supposed to be between 'Sources of information' and 'This report is available from.' 
I saw that you closed #90, but it wasn't fixed in the example that I sent above (see page 5).

**Comment by cgrandin** [comment]
OK sure, for the other issue (#90) make sure you have `copy_sty = true` in the YAML header because all the changes are in the style files.

**Comment by grinnellm** [comment]
Is the default `true`? I don't have that option specified.

**Comment by seananderson** [comment]
Default is true

**Comment by cgrandin** [comment]
I thought you had set it to `false` at one point a year or so ago for Herring. My mistake. But, the change I made definitely fixes it so you may have to re-intstall tinytex.

If you want to put all the newer features into your index.Rmd file, copy paste them from here: https://github.com/pbs-assess/csasdown/blob/7c74f529508275d902b55688e62e599b5de34d61/inst/rmarkdown/templates/sr/skeleton/skeleton.Rmd#L21
