### ISSUE TITLE
Finish integrating SR, Proceedings, and Tech Report options

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/csasdowntex#17]
- [x] Science Responses
- [x] Proceedings / Technical Reports

**Comment by ricardd** [comment]
How high on the list is this? I have generated a Science Response using @grinnellm csas-style-sr and would now like to use csasdown instead in order to have the ability to generate a Word version.

I'd love to contribute but in honesty I wouldn't know where to begin.

**Comment by seananderson** [comment]
Seems pretty high on the list of things to do here, although I really should be working on other projects first. The steps needed to do this would be:

1. Move the .tex and .sty files into the appropriate `inst` folder (I've already done this).
2. Make a `sr` folder as a subdirectory of `inst/rmarkdown` that follows the same structure as the one in `inst/rmarkdown/resdoc`. You could start by copying the `resdoc` one and then editing and paring down as necessary. E.g., we probably don't need the data folder example, or as many .Rmd files, or any appendices.
3. Edit the `skeleton.Rmd` file in `inst/rmarkdown/sr/skeleton/skeleton.Rmd` to have the appropriate metadata for an SR.
4. Edit the file `inst/csas-tex/sr.tex` as needed to pass the .yaml variables from `skeleton.Rmd` (which eventually becomes `index.Rmd` when a user creates a new template) into the .tex file. Take a look at the `res-doc.tex` file for an example. See, e.g. `$year$`.
5. Create `sr_pdf()` and `sr_docx()` in `R/utils.R` that mimic `resdoc_pdf()` etc but point to the appropriate tex and docx templates. The yaml will then be `output: csasdown::sr_pdf()`, for example, in `skeleton.Rmd` / `index.Rmd`.
6. Test it and see what works and what doesn't. We may or may not need to do some editing and re-factoring of `R/utils.R`, `fix_envs()`. I can help.
7. Add unit tests.

Technical reference: https://bookdown.org/yihui/bookdown/

**Comment by ricardd** [comment]
@seananderson I will get started with the steps that you outlined, but will do so on my own branch and will  open a pull request before changes are integrated in the master branch.

**Comment by ricardd** [comment]
@seananderson I have been using the Tech Report style file and will not work on integrating it in the csasdown package. Thanks for merging pull request #25 into the master branch, and for the guidance and help.

**Comment by ricardd** [comment]
@seananderson I have created pull request #26 that includes my attempt at including the TechReport to the csasdown package. I am aware that it doesn't work now but would like you to have a look and see what is wrong. 

It would help to briefly define how the different components in the package fit together (e.g. skeleton.Rmd, _bookdown.yml, template.yaml, ...).

**Comment by seananderson** [comment]
I wrote a response to this yesterday but it seems like I must have closed the tab without submitting it.

skeleton.Rmd gets turned into index.Rmd and becomes the master markdown file for the user.

_bookdown.yml defines some options for bookdown with the most important one being which .Rmd files to combine. More information: https://bookdown.org/yihui/bookdown/configuration.html

template.yaml: I'm not exactly sure what this one does but my best guess is that it defines what you see in a menu item if you create a new bookdown project from within RStudio.

This looks useful for parts of the translation:
https://bookdown.org/yihui/bookdown/internationalization.html

**Comment by seananderson** [comment]
Oh, the other thing I wrote yesterday:

In this file:
https://github.com/pbs-assess/csasdown/blob/master/R/utils.R

The functions such as `resdoc_pdf()` call bookdown with appropriate arguments.

The tricky function is `fix_envs()`. This function operates on the .tex file right before it gets compiled because of `options(bookdown.post.latex = fix_envs)`.

The variable `x` in `fix_envs()` is a character vector where each element is a line of the .tex file. We can then do manipulation on the .tex file to make any changes necessary to be CSAS compliant. If you put a `browser()` in there or use some other debugging technique like `debugonce()` and you render the document from the command line (not from the knit button) then you can pop out in the function and look at `x` and adjust regular expressions as needed.

I should grab this type of information and put it in the wiki along with the description of how to add a new report type.

**Comment by seananderson** [comment]
@grinnellm , can you look at the technical report and science response versions and see if everything looks right? They should now be integrated in the master branch.

Switch to some directory you can test in and then

```r
rmarkdown::draft("index.Rmd", template = "sr", 
  package = "csasdown", create_dir = TRUE, edit = FALSE)
```

Then render `index/index.Rmd` via the RStudio knit button or `bookdown::render_book("index.Rmd")`. Look in `index/_book/`. Then try adjusting the YAML to

```
 csasdown::sr_word:
    french: false
```

and

```
 csasdown::sr_word:
    french: true
```

Same thing for

```r
rmarkdown::draft("index.Rmd", template = "techreport", 
  package = "csasdown", create_dir = TRUE, edit = FALSE)
```

Next step is to get the French resdoc Word, and the French resdoc, techreport, and SR TeX versions working.

**Comment by ricardd** [comment]
I am submitting another pull request (pull request #27) that adds an approval section between Contributors and Sources of Information.

@seananderson and @grinnellm, please review my changes and merge if appropriate.

**Comment by grinnellm** [comment]
Very slick, I like it. However, it seems like there are quite a few issues for both the SR and TR versions. Would you like me to start making Issues, or some other approach?

**Comment by seananderson** [comment]
If it’s a whole bunch of little things then why don’t you make a checklist in this thread: https://help.github.com/articles/about-task-lists/

And we can tick things off as we find time to fix them. If something seems like it will be a bigger deal to fix then we can pull it out into another issue.

**Comment by seananderson** [comment]
Also, for the most part, there isn’t anything we can do about the Word format output but we should be able to fix just about anything on the LaTeX output.

**Comment by grinnellm** [comment]
Perfect, will do:) I didn't even try the Word output (or French) yet!

**Comment by ricardd** [comment]
@grinnellm did you try to compile the SR example from csasdown? I don't see the contributors being added to the output.

I was hoping to move the SR I am currently working on to csasdown but I now realise that we are not there just yet.

**Comment by seananderson** [comment]
I see the contributors in the output from the master branch:

![image](https://user-images.githubusercontent.com/19349/50358059-0e666b00-0526-11e9-8dce-3bb5be0a2e75.png)

`First last affiliation` is the value passed in the yaml.

**Comment by seananderson** [comment]
Oh, I see what you've done there. It will work with the PDF format but not with the Word format because the Word output format will ignore all the TeX commands like `\rdContributors{}`. If we really want to pass variables through like that that need to appear in the middle of the document in both the PDF and Word formats then I think we need to pass it as an RMarkdown param list format so it's available to us as an R object. Similar to what I've done here: https://github.com/pbs-assess/cpue-reports/blob/master/cpue-report.Rmd#L6-L14

**Comment by seananderson** [comment]
Frankly, the better solution here, unless the contributors need some special formatting that we need to surround with TeX, is just to write out the contributors in the contributors .md file instead of trying to pass it via the yaml.

**Comment by ricardd** [comment]
@seananderson, understood. There is no reason to pass contributors via the yaml so I will just add them to the .md file. There are a number of other things that similarly do not appear in the Word output (e.g. approver).

**Comment by seananderson** [comment]
I fixed that here: https://github.com/pbs-assess/csasdown/commit/54d19f33321c051abe33ee689e5a72326b1a29f4

It's that or we start playing with the params list, but I'm not sure it's worth it here

**Comment by ricardd** [comment]
on another note, for the French version of documents, we will also need a separate .bst file so that "and" can appear as "et" both in the inline references and in the bibliography.

**Comment by seananderson** [comment]
Short things like months or days could be easily passed into the params list and pasted together as R objects in the text. It's really just the list of contributors that would be a nightmare to pass that way. Perhaps we want to set up a csv and read it into a properly formatted table for the contributors.

**Comment by ricardd** [comment]
@seananderson could you also please check the pull requests so I can catch up with the master branch?

**Comment by ricardd** [comment]
I am tempted to close this issue as I have so far produced a Science Response, a Research Document and now a Technical Report using csasdown, but I still get this on my TechReport:

```
Output created: _book/techreport.pdf
Warning message:
`% begin_abstract_csasdown` or `% end_abstract_csasdown`` not found in `templates/csas.tex` 
```

**Comment by ricardd** [comment]
and the references in the rendered PDF do not look properly formatted. 

Does the .sty file used override the way the references look like?

**Comment by seananderson** [comment]
References in which rendered PDF don't look properly formatted?

I just fixed the warning for the tech report.

**Comment by ricardd** [comment]
Forget what I said about the references, they are fine.

Having now used csasdown and assembled the holy trinity (ResDoc, SR and TechReport), I am closing this issue.

**Comment by ricardd** [comment]
I updated csasdown, but I still get this warning:
```
Output created: _book/techreport.pdf
Warning message:
`% begin_abstract_csasdown` or `% end_abstract_csasdown`` not found in `templates/csas.tex`
```

Wouldn't the csas.tex file be updated automatically, the same way that the .sty files are updated for ResDocs?

**Comment by ricardd** [comment]
And the first reference has strange indentation:
<img width="424" alt="Capture" src="https://user-images.githubusercontent.com/1110182/55482474-fc9f6400-55fa-11e9-9144-3fd54c2ed245.PNG">
